components:
  schemas:
    tickets:
      type: object
      properties:
        code:
          type: string
          description: codigo del ticket
        purchase_datetime:
          type: string
          description: Fecha y hora de compra
        amount:
          type: number
          description: Total de la compra
        purchaser:
          type: string
          description: Correo del comprador
      required:
        - code
        - purchase_datetime
        - amount
        - purchaser

  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: token

  responses:
    successRes:
      description: Respuesta exitosa
      type: object
      properties:
        error:
          type: boolean
          description: Estado de la solicitud
        data:
          $ref: "#/components/schemas/tickets"
        message:
          type: string
          description: Descripci贸n de la operaci贸n realizada
      example:
        error: false
        data:
          _id: "ID del ticket"
          code: "codigo unico"
          price: "precio total"
          purchaser: "ID del comprador"
        message: "Ticket created succesfully"

  errorResponses:
    errorRes:
      description: Respuesta fallida
      type: object
      properties:
        error:
          type: boolean
          description: Estado de la solicitud
        status:
          type: number
          description: Codigo de status
        message:
          type: string
          description: Descripci贸n de la operaci贸n realizada
      example:
        error: true
        status: 500
        message: "Server error"

paths:
  /api/auth/tickets:
    post:
      summary: Crear un nuevo ticket
      tags:
        - Ticket
      requestBody:
        required: true
        description: Objeto con las propiedades de la compra
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tickets"
      responses:
        "200":
          description: Ticket creado exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/responses/successRes"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/errorRes"
    get:
      summary: Obtener total del ticket
      tags:
        - Ticket
      requestBody:
        required: true
        description: Objeto con el total del ticket
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/tickets"
      responses:
        "200":
          description: Total obtenido exitosamente
          content:
            application/json:
              schema:
                $ref: "#/components/responses/successRes"
        "500":
          description: Error interno del servidor
          content:
            application/json:
              schema:
                $ref: "#/components/errorResponses/errorRes"
